version: '3.8'

services:
  app:
    build:
      context: .
    container_name: node_app
    environment:
      DATABASE_URL: postgresql://postgres:Kelompok1Database@database:5432/moviesdb
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network

  database:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kelompok1Database
      POSTGRES_DB: moviesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_dump_utf8.sql:/docker-entrypoint-initdb.d/database_dump.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
