version: '3.8'

services:
  app:
    build:
      context: .
    container_name: node_app
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: Kelompok1Database
      DATABASE_NAME: moviesdb
    ports:
      - "3000:3000" # Map port aplikasi Node.js
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kelompok1Database
      POSTGRES_DB: moviesdb
    ports:
      - "5432:5432" # Map port PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
